<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFz7jagy\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFz7jagy/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerFz7jagy.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerFz7jagy\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerFz7jagy\appDevDebugProjectContainer([
    'container.build_hash' => 'Fz7jagy',
    'container.build_id' => '5a10ed1c',
    'container.build_time' => 1727085968,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFz7jagy');
